[package]
name = "redis_session"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-session = "0.5"
actix-redis = "0.10"

dotenv = "0.15.0"
env_logger = "0.9"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
actix-test = "0.1.0-beta.11"
time = "0.3.7"
