version: "3.9"
services:
  web:
    build: .
    expose:
      - 8080
    ports:
      - "5000:8080"
    volumes:
      - ./:/app
      - /app/target
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: "redis"
